name: CI cache advance

on:
    push:
        branches:
            - 'main'

jobs:
    ci:
        name: Running CI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: v20.x.x

            - name: Get node version
              id: node
              run: |
                  echo "::set-output name=version::$(node -v)"

            - name: Get node_modules cache
              uses: actions/cache@v4
              id: node_modules
              with:
                  path: |
                      **/node_modules
                  # Adding node version as cache key
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

            - run: yarn install
            - run: yarn test
